### ISSUE TITLE
jQuery "$(window).load" deprecated since 1.8

### ISSUE THREAD

**Issue by brianferguson** [MrGabatt/EleganceForPhpbb33#1]
jQuery 1.8 deprecated the `$(window).load` function, and was removed in 3.0.
[https://api.jquery.com/load-event/](https://api.jquery.com/load-event/)

It is used here:
[https://github.com/MrGabatt/EleganceForPhpbb33/blob/master/elegance/template/forum_fn.js#L1754](https://github.com/MrGabatt/EleganceForPhpbb33/blob/master/elegance/template/forum_fn.js#L1754)

You can replace it with: `$(window).on('load', function() ...`

-Brian

**Comment by MrGabatt** [comment]
Fixed in last version. Thanks.
