### ISSUE TITLE
User icon overlapping user nick name in header

### ISSUE THREAD

**Issue by zpintar** [MrGabatt/EleganceForPhpbb33#2]
It's look like that first letter of nick overlapping icon image - see in red circle

![user-icon](https://user-images.githubusercontent.com/5229470/73049440-e8c03980-3e7c-11ea-94be-79afb41632bb.jpg)

**Comment by brianferguson** [comment]
We had the same issue with our board, but it only seemed to show on Chrome (not Firefox). We didn't test on other browsers.

We also had a "Q" behind the hamburger menu (Quick links menu).

We came up with a [solution](https://github.com/rainmeter/phpbb32-rainmeter-style/commit/6a76205dd9f29630e05b8f73abff8301035e36da) for our modified board, but I am not sure if it will work for everyone.

-Brian

**Comment by MrGabatt** [comment]
Hello

I had successfully reproduced the problem, but by the time I look into it, the problem seems to be gone. A Chrome update? Has the problem also disappeared for you?

**Comment by zpintar** [comment]
> Hello
> 
> I had successfully reproduced the problem, but by the time I look into it, the problem seems to be gone. A Chrome update? Has the problem also disappeared for you?

Yes, after Chrome update from v79 to v80 the problem was gone.

**Comment by MrGabatt** [comment]
Great!

**Comment by MrGabatt** [comment]
Was a Chrome issue.
